### PR TITLE
Switch to ReactNative Linking API

### PR DESCRIPTION
**Pull request by mxstbr**
Based on https://docs.expo.io/versions/latest/guides/linking.html

Using this component throw an error right now.

### CODE REVIEW

**Comment by mxstbr** [comment]
Could also use the WebBrowser.openAsync API I guess, whatever you prefer.

**Comment by brentvatne** [comment]
@mxstbr - yikes this package is old, we haven't used it in years 😅 

`Linking` is most consistent with what the original purpose was so I merged with that. That said, this package is not particularly useful, and you're probably better served by just pulling the code into your app.

**Comment by mxstbr** [comment]
🤷‍♂️ Maybe mention that in the README? I tried using it and got a cryptic error 😅

**Comment by brentvatne** [comment]
the README says this now:

> This component does almost nothing, please view the source in link.js. You may just want to copy the source into your project and customize rather than install it from npm.

**Pull request merged**
